### ISSUE TITLE
Not working in 8.4

### ISSUE THREAD

**Issue by crecord** [roymacdonald/ofxCameraSaveLoad#2]
Thanks for the library. It is just what I am looking for, but I am having some issues with it in 8.4

 ofxCameraSaveLoad doesn't show up in the project generator or on the new OF menu in xcode. When I add the library manually it says:

Undefined symbols for architecture i386:
  "ofxSaveCamera(ofEasyCam&, std::string)", referenced from:
      ofApp::keyPressed(int) in ofApp.o
  "ofxLoadCamera(ofEasyCam&, std::string)", referenced from:
      ofApp::setup() in ofApp.o
      ofApp::keyPressed(int) in ofApp.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by roymacdonald** [comment]
Hi, not sure why it is not showing on PG or the OF menu. Are you sure you placed it in the addons folder and not inside another one? If you add it manually make sure that the .cpp file is compiling for your target; when you drag the files into xcode a dialog pops, there check the box to add these files to your targets. If you already have the files in xcode, select the cpp file and on the right pane youll find a checkbox for adding it to your target. 
Best!

**Comment by crecord** [comment]
The addon was in the correct folder. The problem was that the OF menu in xcode was pointing to an older version of xcode and not the most recent one on my computer. Once I fixed this by resetting the addons path in the OF menu it worked just fine with the OF menu and project generator. 
Compiling for the target after manually adding the addon also worked and I'm glad I know that trick now.

Silly mistake.
Thank you for your help.
